// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn22brKnlHRGzgO3Bk4BwPLmtqGVXpvlU',
    appId: '1:752935498000:web:ae5d47c3a618c1acdf3595',
    messagingSenderId: '752935498000',
    projectId: 'praktikum-pbm-123',
    authDomain: 'praktikum-pbm-123.firebaseapp.com',
    storageBucket: 'praktikum-pbm-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClo3v5Y-xkLmSffD2Bmzeip0_PgKZ27UI',
    appId: '1:752935498000:android:4df023cc5ee01bf1df3595',
    messagingSenderId: '752935498000',
    projectId: 'praktikum-pbm-123',
    storageBucket: 'praktikum-pbm-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX_Nk4TW4cKuXo9uBmw5J2YmoiqpgoH9o',
    appId: '1:752935498000:ios:72080e5e7b7c3e1adf3595',
    messagingSenderId: '752935498000',
    projectId: 'praktikum-pbm-123',
    storageBucket: 'praktikum-pbm-123.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX_Nk4TW4cKuXo9uBmw5J2YmoiqpgoH9o',
    appId: '1:752935498000:ios:72080e5e7b7c3e1adf3595',
    messagingSenderId: '752935498000',
    projectId: 'praktikum-pbm-123',
    storageBucket: 'praktikum-pbm-123.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn22brKnlHRGzgO3Bk4BwPLmtqGVXpvlU',
    appId: '1:752935498000:web:975918de50455dcbdf3595',
    messagingSenderId: '752935498000',
    projectId: 'praktikum-pbm-123',
    authDomain: 'praktikum-pbm-123.firebaseapp.com',
    storageBucket: 'praktikum-pbm-123.firebasestorage.app',
  );

}